export const TransferTableColumn = [
  {
    id: 1,
    label: "NO",
    col: "col1",
  },
  {
    id: 2,
    label: "EGG NUMBER",
    col: "col2",
  },
  {
    id: 3,
    label: "STATUS",
    col: "col3",
  },
  {
    id: 4,
    label: "SPECIES",
    col: "col4",
  },
  {
    id: 5,
    label: "TRANSFERED FROM",
    col: "col5",
  },
  {
    id: 6,
    label: "DATE",
    col: "col6",
  },
  {
    id: 7,
    label: "RECEIVING AT",
    col: "col7",
  },
  {
    id: 8,
    label: "NURSERY",
    col: "col8",
  },
];

export const TransferTableRow = [
  {
    no: "1",
    eggnumber: "0273/24",
    status: "Completed",
    species: "rainbow Lorikeet",
    from: "Site Name XYZ",
    at: "Site Name XYZ",
    date: "10 Apr 24",
    nursery: "NUR123",
  },
  {
    no: "2",
    eggnumber: "0273/24",
    status: "Completed",
    species: "rainbow Lorikeet",
    from: "Site Name XYZ",
    at: "Site Name XYZ",
    date: "10 Apr 24",
    nursery: "NUR123",
  },
  {
    no: "3",
    eggnumber: "0273/24",
    status: "Cancelled",
    species: "rainbow Lorikeet",
    from: "Site Name XYZ",
    at: "Site Name XYZ",
    date: "10 Apr 24",
    nursery: "NUR123",
  },
  {
    no: "4",
    eggnumber: "0273/24",
    status: "In progress",
    species: "rainbow Lorikeet",
    from: "Site Name XYZ",
    at: "Site Name XYZ",
    date: "10 Apr 24",
    nursery: "NUR123",
  },
  {
    no: "5",
    eggnumber: "0273/24",
    status: "Completed",
    species: "rainbow Lorikeet",
    from: "Site Name XYZ",
    at: "Site Name XYZ",
    date: "10 Apr 24",
    nursery: "NUR123",
  },
  {
    no: "6",
    eggnumber: "0273/24",
    status: "Completed",
    species: "rainbow Lorikeet",
    from: "Site Name XYZ",
    at: "Site Name XYZ",
    date: "10 Apr 24",
    nursery: "NUR123",
  },
  {
    no: "7",
    eggnumber: "0273/24",
    status: "Completed",
    species: "rainbow Lorikeet",
    from: "Site Name XYZ",
    at: "Site Name XYZ",
    date: "10 Apr 24",
    nursery: "NUR123",
  },
  {
    no: "8",
    eggnumber: "0273/24",
    status: "Cancelled",
    species: "rainbow Lorikeet",
    from: "Site Name XYZ",
    at: "Site Name XYZ",
    date: "10 Apr 24",
    nursery: "NUR123",
  },
  {
    no: "9",
    eggnumber: "0273/24",
    status: "Completed",
    species: "rainbow Lorikeet",
    from: "Site Name XYZ",
    at: "Site Name XYZ",
    date: "10 Apr 24",
    nursery: "NUR123",
  },
  {
    no: "10",
    eggnumber: "0273/24",
    status: "Completed",
    species: "rainbow Lorikeet",
    from: "Site Name XYZ",
    at: "Site Name XYZ",
    date: "10 Apr 24",
    nursery: "NUR123",
  },
  {
    no: "11",
    eggnumber: "0273/24",
    status: "In Progress",
    species: "rainbow Lorikeet",
    from: "Site Name XYZ",
    at: "Site Name XYZ",
    date: "10 Apr 24",
    nursery: "NUR123",
  },
  {
    no: "12",
    eggnumber: "0273/24",
    status: "Completed",
    species: "rainbow Lorikeet",
    from: "Site Name XYZ",
    at: "Site Name XYZ",
    date: "10 Apr 24",
    nursery: "NUR123",
  },
  {
    no: "13",
    eggnumber: "0273/24",
    status: "Completed",
    species: "rainbow Lorikeet",
    from: "Site Name XYZ",
    at: "Site Name XYZ",
    date: "10 Apr 24",
    nursery: "NUR123",
  },
  {
    no: "14",
    eggnumber: "0273/24",
    status: "Completed",
    species: "rainbow Lorikeet",
    from: "Site Name XYZ",
    at: "Site Name XYZ",
    date: "10 Apr 24",
    nursery: "NUR123",
  },
];

export const SpeciesTableColumn = [
  {
    id: 1,
    label: "NO",
    col: "col1",
  },
  {
    id: 2,
    label: "SPECIES",
    col: "col2",
  },
  {
    id: 3,
    label: "TOTAL EGGS",
    col: "col3",
  },
  {
    id: 4,
    label: "IN NEST",
    col: "col4",
  },
  {
    id: 5,
    label: "IN NURSEY",
    col: "col5",
  },
  {
    id: 6,
    label: "GOOD CONDITION",
    col: "col6",
  },
  {
    id: 7,
    label: "DISCARDED",
    col: "col7",
  },
  {
    id: 8,
    label: "TILL DATE",
    col: "col8",
  },
];

export const SpeciesTableRow = [
  {
    no: "1",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "2",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "3",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "4",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "5",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "6",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "7",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "8",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "9",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "10",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "11",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "12",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "13",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "14",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "15",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "16",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "17",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "18",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "19",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "20",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "21",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "22",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "23",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "24",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "25",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "26",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "27",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "28",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "29",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "30",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
  {
    no: "31",
    totaleggs: "24",
    innest: "10",
    species: "rainbow Lorikeet",
    innursery: "14",
    goodcondition: "18",
    discarded: "6",
    tilldate: "10 Apr 24",
  },
];
